-- MySQL Script generated by MySQL Workbench
-- Fri Dec  5 13:53:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema virt_assist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema virt_assist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `virt_assist` DEFAULT CHARACTER SET utf8mb3 ;
USE `virt_assist` ;

-- -----------------------------------------------------
-- Table `virt_assist`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virt_assist`.`projects` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `desc` VARCHAR(4096) NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `virt_assist`.`sub_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virt_assist`.`sub_tasks` (
  `st_ip` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `desc` VARCHAR(4096) NULL,
  PRIMARY KEY (`st_ip`, `project_id`),
  INDEX `fk_in_progress_projects_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_in_progress_projects`
    FOREIGN KEY (`project_id`)
    REFERENCES `virt_assist`.`projects` (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `virt_assist`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virt_assist`.`roles` (
  `r_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(1024) NULL,
  PRIMARY KEY (`r_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virt_assist`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virt_assist`.`people` (
  `peple_id` INT NOT NULL AUTO_INCREMENT,
  `fio` VARCHAR(128) NOT NULL,
  `date_b` DATE NOT NULL,
  `exp_years` INT NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `desc` VARCHAR(4096) NULL,
  `tg` VARCHAR(128) NOT NULL,
  `r_id` INT NOT NULL,
  PRIMARY KEY (`peple_id`, `tg`, `r_id`),
  INDEX `fk_people_roles1_idx` (`r_id` ASC) VISIBLE,
  CONSTRAINT `fk_people_roles1`
    FOREIGN KEY (`r_id`)
    REFERENCES `virt_assist`.`roles` (`r_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `virt_assist`.`proffesions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virt_assist`.`proffesions` (
  `prof_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `desc` VARCHAR(45) NULL,
  PRIMARY KEY (`prof_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `virt_assist`.`workers_exp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virt_assist`.`workers_exp` (
  `w_id` INT NOT NULL AUTO_INCREMENT,
  `peple_id` INT NOT NULL,
  `prof_id` INT NOT NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  PRIMARY KEY (`w_id`, `peple_id`, `prof_id`),
  INDEX `fk_workers_people1_idx` (`peple_id` ASC) VISIBLE,
  INDEX `fk_workers_proffesions1_idx` (`prof_id` ASC) VISIBLE,
  CONSTRAINT `fk_workers_people1`
    FOREIGN KEY (`peple_id`)
    REFERENCES `virt_assist`.`people` (`peple_id`),
  CONSTRAINT `fk_workers_proffesions1`
    FOREIGN KEY (`prof_id`)
    REFERENCES `virt_assist`.`proffesions` (`prof_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `virt_assist`.`in_progress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virt_assist`.`in_progress` (
  `inp_id` INT NOT NULL AUTO_INCREMENT,
  `st_ip` INT NOT NULL,
  `peple_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`inp_id`, `st_ip`, `peple_id`),
  INDEX `fk_in_progress_sub_tasks1_idx` (`st_ip` ASC) VISIBLE,
  INDEX `fk_in_progress_people1_idx` (`peple_id` ASC) VISIBLE,
  CONSTRAINT `fk_in_progress_sub_tasks1`
    FOREIGN KEY (`st_ip`)
    REFERENCES `virt_assist`.`sub_tasks` (`st_ip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_in_progress_people1`
    FOREIGN KEY (`peple_id`)
    REFERENCES `virt_assist`.`people` (`peple_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
