-- MySQL Script generated by MySQL Workbench
-- Sat Nov 29 19:19:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema virt_assist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema virt_assist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `virt_assist` DEFAULT CHARACTER SET utf8 ;
USE `virt_assist` ;

-- -----------------------------------------------------
-- Table `virt_assist`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virt_assist`.`people` (
  `peple_id` INT NOT NULL AUTO_INCREMENT,
  `fio` VARCHAR(128) NULL,
  `date_b` DATE NULL,
  `exp_years` INT NULL,
  `email` VARCHAR(128) NULL,
  `desc` VARCHAR(4096) NULL,
  PRIMARY KEY (`peple_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virt_assist`.`proffesions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virt_assist`.`proffesions` (
  `prof_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `desc` VARCHAR(45) NULL,
  PRIMARY KEY (`prof_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virt_assist`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virt_assist`.`projects` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `desc` VARCHAR(4096) NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virt_assist`.`workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virt_assist`.`workers` (
  `w_id` INT NOT NULL AUTO_INCREMENT,
  `people_peple_id` INT NOT NULL,
  `proffesions_prof_id` INT NOT NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  PRIMARY KEY (`w_id`, `people_peple_id`, `proffesions_prof_id`),
  INDEX `fk_workers_people1_idx` (`people_peple_id` ASC) VISIBLE,
  INDEX `fk_workers_proffesions1_idx` (`proffesions_prof_id` ASC) VISIBLE,
  CONSTRAINT `fk_workers_people1`
    FOREIGN KEY (`people_peple_id`)
    REFERENCES `virt_assist`.`people` (`peple_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workers_proffesions1`
    FOREIGN KEY (`proffesions_prof_id`)
    REFERENCES `virt_assist`.`proffesions` (`prof_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virt_assist`.`in_progress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virt_assist`.`in_progress` (
  `inp_ip` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `workers_w_id` INT NOT NULL,
  PRIMARY KEY (`inp_ip`, `project_id`, `workers_w_id`),
  INDEX `fk_in_progress_projects_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_in_progress_workers1_idx` (`workers_w_id` ASC) VISIBLE,
  CONSTRAINT `fk_in_progress_projects`
    FOREIGN KEY (`project_id`)
    REFERENCES `virt_assist`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_in_progress_workers1`
    FOREIGN KEY (`workers_w_id`)
    REFERENCES `virt_assist`.`workers` (`w_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
